#{
  import "requirements.typ": wut-thesis, glossarium, drafting
  import wut-thesis: wut-thesis, acknowledgements, figure-outline, table-outline, appendix
  import "utils.typ": flex-caption-styles, todo, glossary-outline
  import "glossary.typ": glossary
  import glossarium: make-glossary, register-glossary
  import drafting: note-outline, set-margin-note-defaults

  show: make-glossary
  register-glossary(glossary)
  show: flex-caption-styles


  /** Drafting

    The "draft" variable is used to change the coloring of links, show TODOs (both in
    the thesis and TODO outline), as well as DRAFT in the header and the title. This
    should be true until the final version is handed-in.

    The "in-print" variable is used to generate a PDF file for physical printing (it adds
    bigger margins on the binding part of the page and changes the numbering placement).
    It should be set to `false` unless you want to create a version of the PDF file for
    physical print, in which case set it to `true`. To prepare a PDF file for the
    final hand-in (that is to upload it to APD/onedrive) please set this variable to
    `false`. variable to false.

  **/
  let draft = false
  let in-print = false
  set-margin-note-defaults(hidden: not draft)

  /// Set the languages of your studies and thesis.
  let lang = (
    /// Language in which you studied, influences the language of the titlepage.
    studies: "en",
    /// Language in which your thesis is written, influences the rest of the text (i.e.
    /// abstracts order, captions/references supplements, hyphenation etc).
    thesis: "en"
  )

  show: wut-thesis.with(
    draft: draft,
    in-print: in-print,
    lang: lang,
    // Adjust the following fields accordingly to your thesis
    titlepage-info: (
      thesis-type: "master", // or "bachelor" or "master"
      program: "Computer Science",
      //specialisation: "Systemy Internetowe Wspomagania Zarządzania",
      institute: "The Institute of Control and Computation Engineering",
      supervisor: "dr hab. inż. Mariusz Kaleta",
      // The optional advisor of the thesis, this will be typeset as
      //  `consultation`/`konsultacje` in the titlepage.
      advisor: none, // or `none` if there were no advisors
      faculty: "weiti", // see the tutorial section of this thesis for a list of all possible faculty shorthands
      index-number: "341048",
      date: datetime.today(), // not today: datetime(year: 1969, month: 9, day: 6,)
    ),
    // if you don't want to create a title page (e.g. if you need to use the one
    // generated by APD) then comment the above `titlepage-info` lines and instead
    // uncomment this line:
    // titlepage-info: none,
    author: "Piotr Wierciński",
    // Note that regardless of the language of your thesis you need to fill in all the
    // fields below - both *.en and *.pl
    title: (
      en: "Evolving Graph Neural Network Architectures \n with Cartesian Genetic Programming \n for the Capacitated Vehicle Routing Problem",
      pl: "Ewolucja architektur grafowych sieci neuronowych z wykorzystaniem kartezjańskiego programowania genetycznego w zastosowaniu do problemu trasowania pojazdów z ograniczoną pojemnością",
    ),
    abstract: (
      en: [
      This thesis investigates whether Cartesian Genetic Programming (CGP) can be effectively used as a Neural Architecture Search (NAS) method for evolving neural network encoder architectures for the Capacitated Vehicle Routing Problem (CVRP). The work builds upon the model proposed by Kool et al., which uses a transformer-based encoder to solve routing problems. The architecture search is applied only to the encoder, while the decoder and the general training procedure remain unchanged.

      The implemented approach uses CGP to represent and evolve encoder architectures as computational graphs. Due to the high computational cost of training neural networks, a reduced proxy training setup is used during architecture search, while selected architectures are later trained from scratch using a full training configuration.

      Two experiments are conducted. First, CGP-based architecture search is compared with random search within the same search space and under the same computational budget. Across 10 independent runs, CGP consistently outperformed random search under proxy evaluation. Even the worst-performing CGP run achieved a better score than the best-performing random search run. However, the ranking obtained during proxy evaluation is only weakly preserved after full training, demonstrating a limitation of the proxy evaluation method.

      In the second experiment, CGP is used to evolve an existing single-layer transformer encoder. The search discovers several structurally different architectures that remain competitive after full training. In particular, EVO-3 achieves a better routing score than the initial transformer on every evaluated problem size, including CVRP10, CVRP20, CVRP50, and CVRP100, while using almost the same number of encoder parameters. The evolved architectures also remain competitive with the original three-layer transformer encoder, with EVO-3 and EVO-6 achieving slightly better scores on its original CVRP100 test dataset.

      Overall, the results show that CGP-based NAS can guide architecture search more effectively than random search under the considered experimental setup and can discover effective modifications of an existing transformer-based encoder. However, the relatively small differences after full training and the limited number of full evaluations mean that further evaluation is needed before drawing more general conclusions.

      ],
      pl: [
        Niniejsza praca bada, czy kartezjańskie programowanie genetyczne (CGP) może być skutecznie wykorzystane jako metoda automatycznego wyszukiwania architektur sieci neuronowych (NAS) do ewolucji architektur enkodera dla problemu marszrutyzacji pojazdów z ograniczoną ładownością (CVRP). Praca bazuje na modelu zaproponowanym przez Koola i in., który wykorzystuje enkoder oparty na architekturze transformer do rozwiązywania problemów marszrutyzacji. Wyszukiwanie architektury jest ograniczone wyłącznie do enkodera, podczas gdy dekoder oraz ogólny proces uczenia pozostają niezmienione. 

        Zaimplementowane podejście wykorzystuje CGP do reprezentowania i ewolucji architektur enkodera w postaci grafów obliczeniowych. Ze względu na wysoki koszt treningu podczas wyszukiwania stosowana jest uproszczona konfiguracja proxy, natomiast wybrane architektury są następnie trenowane od podstaw przy użyciu pełnej konfiguracji.

        Przeprowadzono dwa eksperymenty. W pierwszym wyszukiwanie architektur oparte na CGP porównano z wyszukiwaniem losowym przy wykorzystaniu tej samej przestrzeni wyszukiwania i tego samego budżetu obliczeniowego. W 10 niezależnych uruchomieniach CGP konsekwentnie osiągało lepsze wyniki niż wyszukiwanie losowe w ewaluacji proxy. Nawet najgorszy wynik uzyskany przez CGP był lepszy od najlepszego wyniku wyszukiwania losowego. Ranking uzyskany podczas ewaluacji proxy został jednak tylko w niewielkim stopniu zachowany po pełnym treningu, co wskazuje na ograniczenie zastosowanej metody ewaluacji proxy.

        W drugim eksperymencie CGP wykorzystano do ewolucji istniejącego jednowarstwowego enkodera transformer. Wyszukiwanie pozwoliło odkryć kilka różniących się strukturalnie architektur, które pozostały konkurencyjne po pełnym treningu. W szczególności EVO-3 uzyskała lepszy wynik niż początkowy transformer dla każdego badanego rozmiaru problemu, w tym CVRP10, CVRP20, CVRP50 oraz CVRP100, przy niemal takiej samej liczbie parametrów enkodera. Ewoluowane architektury pozostały również konkurencyjne względem oryginalnego trzywarstwowego transformer, a EVO-3 i EVO-6 uzyskały nieznacznie lepsze wyniki na jego oryginalnym zbiorze testowym CVRP100.

        Ogólnie uzyskane wyniki pokazują, że NAS oparty na CGP może skuteczniej kierować procesem wyszukiwania architektur niż wyszukiwanie losowe w ramach rozważanej konfiguracji eksperymentalnej oraz pozwala odkrywać skuteczne modyfikacje istniejącego enkodera opartego na architekturze transformer. Jednocześnie stosunkowo niewielkie różnice po pełnym treningu oraz ograniczona liczba pełnych ewaluacji wskazują na potrzebę dalszych badań przed sformułowaniem bardziej ogólnych wniosków.
      ]
    ),
    keywords: (
      en: ("cartesian genetic programming", "neural architecture search", "graph neural networks"),
      pl: ("kartezjańskie programowanie genetyczne", "neuroewolucja", "grafowe sieci neuronowe")
    ),
  )

  // --- Custom Settings ---
  // if you want to override any settings from the template here is the place to do so,
  // e.g.:
  // Use Comic Sans Font
  // set text(font: "Comic Sans MS")
  // Use nicer microtypography
  set par(justification-limits: (
    tracking: (min: -0.01em, max: 0.02em),
  ))

  include "content/1_Introduction.typ" 
  include "content/2_Theory.typ" 
  include "content/3_Literature.typ" 
  include "content/4_Methodology.typ" 
  include "content/5_Experiments.typ"
  include "content/6_Results.typ"
  include "content/7_Conclusions.typ"
  // --- Main Chapters ---
  // include "content/Tutorial.typ" // Some trivial, but useful snippets
  // include "content/Introduction.typ"
  // include "content/LiteratureReview.typ"
  // include "content/Methodology.typ"
  // include "content/DataCollection.typ"
  // include "content/Analysis.typ"
  // include "content/Conclusion.typ"

  // --- Acknowledgements ---
  // You can put your acknowledgements (pol. podziękowania) here.
  // Below is an example containing acknowledgements for the PLGrid grant.
  // Comment out if not needed.
  // acknowledgements[
  //   We gratefully acknowledge Poland's high-performance Infrastructure PLGrid
  //   #text(fill: red)[(wybierz właściwy ośrodek z listy: ACK Cyfronet AGH, PCSS, CI TASK,
  //     WCSS)] for providing computer facilities and support within computational grant no
  //   #text(fill: red)[(numer grantu)]
  //   #todo[Numer grantu i typ ośrodka]
  // ]

  // --- Bibliography ---
  bibliography("items.bib", style: "ieee")

  // // List of Acronyms - comment out, if not needed (no abbreviations were used).
  glossary-outline(glossary)

  // // List of figures - comment out, if not needed.
  figure-outline(lang.thesis)

  // // List of tables - comment out, if not needed.
  // table-outline(lang.thesis)

  // --- Appendices ---
  // Comment out if not needed.
appendix(
  lang.thesis,
  {
    include "content/Appendix0.typ"
    include "content/Appendix.typ"
    include "content/Appendix2.typ"
  }
)
  // if draft {
  //   set heading(numbering: none)
  //   note-outline(title: "TODOs")
  // }
}
