#{
  import "requirements.typ": wut-thesis, glossarium, drafting
  import wut-thesis: wut-thesis, acknowledgements, figure-outline, table-outline, appendix
  import "utils.typ": flex-caption-styles, todo, glossary-outline
  import "glossary.typ": glossary
  import glossarium: make-glossary, register-glossary
  import drafting: note-outline, set-margin-note-defaults

  show: make-glossary
  register-glossary(glossary)
  show: flex-caption-styles


  /** Drafting

    The "draft" variable is used to change the coloring of links, show TODOs (both in
    the thesis and TODO outline), as well as DRAFT in the header and the title. This
    should be true until the final version is handed-in.

    The "in-print" variable is used to generate a PDF file for physical printing (it adds
    bigger margins on the binding part of the page and changes the numbering placement).
    It should be set to `false` unless you want to create a version of the PDF file for
    physical print, in which case set it to `true`. To prepare a PDF file for the
    final hand-in (that is to upload it to APD/onedrive) please set this variable to
    `false`. variable to false.

  **/
  let draft = true
  let in-print = false
  set-margin-note-defaults(hidden: not draft)

  /// Set the languages of your studies and thesis.
  let lang = (
    /// Language in which you studied, influences the language of the titlepage.
    studies: "pl",
    /// Language in which your thesis is written, influences the rest of the text (i.e.
    /// abstracts order, captions/references supplements, hyphenation etc).
    thesis: "en"
  )

  show: wut-thesis.with(
    draft: draft,
    in-print: in-print,
    lang: lang,
    // Adjust the following fields accordingly to your thesis
    titlepage-info: (
      thesis-type: "master", // or "bachelor" or "master"
      program: "Informatyka",
      specialisation: "Systemy Internetowe Wspomagania Zarządzania",
      institute: "Instytut Automatyki i Informatyki Stosowanej",
      supervisor: "dr hab. inż. Mariusz Kaleta",
      // The optional advisor of the thesis, this will be typeset as
      //  `consultation`/`konsultacje` in the titlepage.
      advisor: none, // or `none` if there were no advisors
      faculty: "weiti", // see the tutorial section of this thesis for a list of all possible faculty shorthands
      index-number: "341048",
      date: datetime.today(), // not today: datetime(year: 1969, month: 9, day: 6,)
    ),
    // if you don't want to create a title page (e.g. if you need to use the one
    // generated by APD) then comment the above `titlepage-info` lines and instead
    // uncomment this line:
    // titlepage-info: none,
    author: "Piotr Wierciński",
    // Note that regardless of the language of your thesis you need to fill in all the
    // fields below - both *.en and *.pl
    title: (
      en: "Evolving Graph Neural Network Architectures with Cartesian Genetic Programming for the Capacitated Vehicle Routing Problem",
      pl: "Ewolucja architektur grafowych sieci neuronowych z wykorzystaniem kartezjańskiego programowania genetycznego w zastosowaniu do problemu trasowania pojazdów z ograniczoną pojemnością",
    ),
    abstract: (
      en: [
        This study explores the use of Cartesian Genetic Programming (CGP) to design a Neural Architecture Search (NAS) method in the context of Graph Neural Networks (GNNs) for solving the Capacitated Vehicle Routing Problem (CVRP).

        The work builds upon the model introduced in "Attention, Learn to Solve Routing Problems!", which uses a generic Transformer architecture in its encoder for solving various classes of routing problems. This study investigates whether more specialized architectures can be discovered and employed for solving CVRP. The neural architecture search is applied only to the encoder component of the network.
        The resulting evolved architectures are compared against randomly generated ones as well as the original architecture from the referenced paper. 
        
        The evolutionary strategy is based on the Cartesian Genetic Programming algorithm whose graph-based representation naturally aligns with the structure of Graph Neural Networks. Due to high computational cost of training architectures for evaluation, a proxy ranking method is employed, using smaller problem instances and reduced number and size of training epochs.

        Models are evaluated and compared against synthetically generated datasets, which is a standard practice in this field.

      ],
      pl: [
        Niniejsza praca bada zastosowanie Kartezjańskiego Programowania Genetycznego (Cartesian Genetic Programming, CGP) w celu zaprojektowania metody poszukiwania architektur sieci neuronowych (Neural Architecture Search, NAS) w kontekście Grafowych Sieci Neuronowych (Graph Neural Networks, GNN) dla problemu marszrutyzacji w wariancie z ograniczoną pojemnością (Capacitated Vehicle Routing Problem, CVRP).

        Praca opiera się na modelu wprowadzonym w pracy "Attention, Learn to Solve Routing Problems!", który używa standardowej architektury Transformera w enkoderze do rozwiązywania różnych klas problemów trasowania pojazdów. W niniejszej pracy algorytm neuroewolucyjny wykorzystywany jest do odkrycia bardziej skutecznych architektur, które mogą być bardziej wyspecjalizowane pod kątem CVRP. Ewolucja modelu obejmuje architekture enkodera.
        Finalne architektury są porównywane zarówno z losowo otrzymanymi, jak i z oryginalną architekturą enkodera z pracy referencyjnej.

        Strategia ewolucji jest oparta na Kartezjańskim Programowaniu Genetycznym, którego struktura grafowa naturalne odpowiada reprezentacji grafowych sieci neuronowych. Z uwagi na wysokie koszty obliczeniowe, wykorzystana jest rankingowa metoda proxy, polegająca na użyciu mniejszych instancji problemu CVRP oraz ograniczonej liczbie epok o mniejszym rozmiarze.

        Modele są ewaluowane na syntetycznie generowanych zbiorach danych, co jest standardową praktyką dla tego zagadnienia.
      ]
    ),
    keywords: (
      en: ("cartesian genetic programming", "neural architecture search", "graph neural networks"),
      pl: ("kartezjańskie programowanie genetyczne", "neuroewolucja", "grafowe sieci neuronowe")
    ),
  )

  // --- Custom Settings ---
  // if you want to override any settings from the template here is the place to do so,
  // e.g.:
  // Use Comic Sans Font
  // set text(font: "Comic Sans MS")
  // Use nicer microtypography
  set par(justification-limits: (
    tracking: (min: -0.01em, max: 0.02em),
  ))

  include "content/1_Introduction.typ" 
  include "content/2_Theory.typ" 
  // --- Main Chapters ---
  include "content/Tutorial.typ" // Some trivial, but useful snippets
  // include "content/Introduction.typ"
  // include "content/LiteratureReview.typ"
  // include "content/Methodology.typ"
  // include "content/DataCollection.typ"
  // include "content/Analysis.typ"
  // include "content/Conclusion.typ"

  // --- Acknowledgements ---
  // You can put your acknowledgements (pol. podziękowania) here.
  // Below is an example containing acknowledgements for the PLGrid grant.
  // Comment out if not needed.
  // acknowledgements[
  //   We gratefully acknowledge Poland's high-performance Infrastructure PLGrid
  //   #text(fill: red)[(wybierz właściwy ośrodek z listy: ACK Cyfronet AGH, PCSS, CI TASK,
  //     WCSS)] for providing computer facilities and support within computational grant no
  //   #text(fill: red)[(numer grantu)]
  //   #todo[Numer grantu i typ ośrodka]
  // ]

  // --- Bibliography ---
  bibliography("items.bib", style: "ieee")

  // List of Acronyms - comment out, if not needed (no abbreviations were used).
  glossary-outline(glossary)

  // List of figures - comment out, if not needed.
  figure-outline(lang.thesis)

  // List of tables - comment out, if not needed.
  table-outline(lang.thesis)

  // --- Appendices ---
  // Comment out if not needed.
  // appendix(lang.thesis, include "content/Appendix.typ")

  if draft {
    set heading(numbering: none)
    note-outline(title: "TODOs")
  }
}
